# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ee59127dd5231f086cf57621232d6c5b3b7009696dcfbb8474ba1c4c3e61ee91608cad3917023fbd4c8f0b2eab93724962916ec598954153d6567142aa0d0b4

test:
  secret_key_base: dd5b66a68c5ec1eb47d30df365c4e732117a176b8327a1bff2841625dee98823d457b1c82e92691f98359a08abf6376a73b6a5d0f2f8a69da39aa979e52fbeb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
